"""
train_and_evaluate.py
=====================
Trains the churn-classification models on the SYNTHETIC gym-membership churn
dataset (generated by generate_data.py), computes REAL evaluation metrics, and
generates the ROC-curve and feature-importance figures.

Run:
    python train_and_evaluate.py

Outputs (in ./outputs/):
    - roc_curves.png
    - feature_importance.png
    - metrics_summary.json

ARCHITECTURE (responsibility-separated, one class = one job)
------------------------------------------------------------
    Config           - all paths / constants in one place
    DatasetBuilder   - STEP 1: load (or generate) data + train/test split
    Preprocessor     - builds the numeric+categorical ColumnTransformer
    ChurnModelTrainer- STEP 2: train + GridSearchCV-tune the 3 models
    ModelEvaluator   - STEP 3: compute metrics (acc/prec/rec/F1/ROC-AUC)
    FigureBuilder    - STEP 4: draw ROC + feature-importance PNGs
    MetricsReporter  - STEP 5: dump metrics_summary.json
    ChurnPipeline    - the orchestrator: runs STEP 1..5 in order

The step order is defined once, in ChurnPipeline.run(). Each class below can be
read, tested, or reused on its own.

This script uses the same modeling logic as gym_churn_classification.ipynb,
so the numbers match the notebook.
"""

import os
import json
import warnings
from dataclasses import dataclass
from typing import Dict, Tuple

import numpy as np
import pandas as pd
import matplotlib

matplotlib.use("Agg")  # headless rendering
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    roc_curve,
)

warnings.filterwarnings("ignore")


# ======================================================================
# Config  -  every path and constant lives here, nothing hard-coded below
# ======================================================================
@dataclass
class Config:
    here: str = os.path.dirname(os.path.abspath(__file__))
    random_state: int = 42
    test_size: float = 0.2
    target: str = "Churn"

    @property
    def output_dir(self) -> str:
        return os.path.join(self.here, "outputs")

    @property
    def data_csv(self) -> str:
        return os.path.join(self.here, "data", "gym_churn.csv")

    @property
    def roc_png(self) -> str:
        return os.path.join(self.output_dir, "roc_curves.png")

    @property
    def fi_png(self) -> str:
        return os.path.join(self.output_dir, "feature_importance.png")

    @property
    def metrics_json(self) -> str:
        return os.path.join(self.output_dir, "metrics_summary.json")


# ======================================================================
# Data structures passed between the steps
# ======================================================================
@dataclass
class Dataset:
    """The 80/20 split, plus the full frame for slide-level stats."""
    frame: pd.DataFrame
    X_train: pd.DataFrame
    X_test: pd.DataFrame
    y_train: pd.Series
    y_test: pd.Series


@dataclass
class TunedModel:
    """A single model after GridSearchCV (fitted, best params chosen)."""
    name: str
    estimator: Pipeline
    best_params: dict


@dataclass
class ModelResult:
    """Everything downstream steps need to know about one model."""
    name: str
    estimator: Pipeline
    best_params: dict
    metrics: Dict[str, float]           # accuracy, precision, recall, f1, roc_auc
    roc: Tuple[np.ndarray, np.ndarray]  # (fpr, tpr)


# ======================================================================
# STEP 1  -  DatasetBuilder: get the data and split it
# ======================================================================
class DatasetBuilder:
    def __init__(self, config: Config):
        self.cfg = config

    def _load_frame(self) -> pd.DataFrame:
        if not os.path.exists(self.cfg.data_csv):
            print("Synthetic CSV not found, generating it now ...")
            import generate_data

            generate_data.main()
        print(f"Loading dataset: {self.cfg.data_csv}")
        return pd.read_csv(self.cfg.data_csv)

    def build(self) -> Dataset:
        df = self._load_frame()
        print(f"Data shape: {df.shape}  |  churn rate: {df[self.cfg.target].mean():.1%}")

        X = df.drop(columns=[self.cfg.target])
        y = df[self.cfg.target]
        X_train, X_test, y_train, y_test = train_test_split(
            X, y,
            test_size=self.cfg.test_size,
            stratify=y,
            random_state=self.cfg.random_state,
        )
        return Dataset(frame=df, X_train=X_train, X_test=X_test,
                       y_train=y_train, y_test=y_test)


# ======================================================================
# Preprocessor  -  scale numeric cols, one-hot encode categorical cols
# ======================================================================
class Preprocessor:
    @staticmethod
    def build(X: pd.DataFrame) -> ColumnTransformer:
        num_cols = X.select_dtypes(include=["number"]).columns.tolist()
        cat_cols = X.select_dtypes(exclude=["number"]).columns.tolist()
        return ColumnTransformer(
            [
                ("num", StandardScaler(), num_cols),
                ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols),
            ]
        )


# ======================================================================
# STEP 2  -  ChurnModelTrainer: train + GridSearchCV-tune each model
# ======================================================================
class ChurnModelTrainer:
    def __init__(self, config: Config):
        self.cfg = config

    def _model_configs(self) -> Dict[str, Tuple[object, dict]]:
        rs = self.cfg.random_state
        return {
            "Logistic Regression": (
                LogisticRegression(max_iter=1000, random_state=rs),
                {"clf__C": [0.01, 0.1, 1, 10]},
            ),
            "Random Forest": (
                RandomForestClassifier(random_state=rs),
                {
                    "clf__n_estimators": [200, 400],
                    "clf__max_depth": [None, 6, 10],
                    "clf__min_samples_split": [2, 5],
                },
            ),
            "SVM (RBF)": (
                SVC(kernel="rbf", probability=True, random_state=rs),
                {"clf__C": [0.1, 1, 10], "clf__gamma": ["scale", 0.01, 0.1]},
            ),
        }

    def train(self, data: Dataset) -> Dict[str, TunedModel]:
        tuned: Dict[str, TunedModel] = {}
        for name, (estimator, param_grid) in self._model_configs().items():
            print(f"\n=== Tuning {name} ===")
            pipe = Pipeline(
                [("prep", Preprocessor.build(data.X_train)), ("clf", estimator)]
            )
            grid = GridSearchCV(
                pipe, param_grid, cv=5, scoring="roc_auc", n_jobs=-1
            )
            grid.fit(data.X_train, data.y_train)
            print(f"best params: {grid.best_params_}")
            tuned[name] = TunedModel(
                name=name,
                estimator=grid.best_estimator_,
                best_params=grid.best_params_,
            )
        return tuned


# ======================================================================
# STEP 3  -  ModelEvaluator: turn fitted models into metrics + ROC data
# ======================================================================
class ModelEvaluator:
    @staticmethod
    def _scores(model: Pipeline, X: pd.DataFrame) -> np.ndarray:
        """Positive-class scores for ROC, via proba or decision_function."""
        if hasattr(model, "predict_proba"):
            return model.predict_proba(X)[:, 1]
        return model.decision_function(X)

    def evaluate(
        self, tuned: Dict[str, TunedModel], data: Dataset
    ) -> Dict[str, ModelResult]:
        results: Dict[str, ModelResult] = {}
        for name, tm in tuned.items():
            y_pred = tm.estimator.predict(data.X_test)
            y_score = self._scores(tm.estimator, data.X_test)

            metrics = {
                "accuracy": accuracy_score(data.y_test, y_pred),
                "precision": precision_score(data.y_test, y_pred),
                "recall": recall_score(data.y_test, y_pred),
                "f1": f1_score(data.y_test, y_pred),
                "roc_auc": roc_auc_score(data.y_test, y_score),
            }
            fpr, tpr, _ = roc_curve(data.y_test, y_score)

            print(
                f"{name}: acc={metrics['accuracy']:.3f} "
                f"prec={metrics['precision']:.3f} rec={metrics['recall']:.3f} "
                f"f1={metrics['f1']:.3f} auc={metrics['roc_auc']:.3f}"
            )
            results[name] = ModelResult(
                name=name,
                estimator=tm.estimator,
                best_params=tm.best_params,
                metrics=metrics,
                roc=(fpr, tpr),
            )
        return results


# ======================================================================
# STEP 4  -  FigureBuilder: draw the ROC + feature-importance PNGs
# ======================================================================
class FigureBuilder:
    def __init__(self, config: Config):
        self.cfg = config

    def plot_roc(self, results: Dict[str, ModelResult]) -> str:
        plt.figure(figsize=(7, 6))
        for name, r in results.items():
            fpr, tpr = r.roc
            plt.plot(fpr, tpr, lw=2, label=f"{name} (AUC = {r.metrics['roc_auc']:.3f})")
        plt.plot([0, 1], [0, 1], "k--", lw=1, label="Random")
        plt.xlabel("False Positive Rate")
        plt.ylabel("True Positive Rate")
        plt.title("ROC Curves — Churn Classifiers")
        plt.legend(loc="lower right")
        plt.grid(alpha=0.3)
        plt.tight_layout()
        plt.savefig(self.cfg.roc_png, dpi=150)
        plt.close()
        print(f"saved {self.cfg.roc_png}")
        return self.cfg.roc_png

    def plot_feature_importance(self, results: Dict[str, ModelResult]) -> pd.Series:
        best_rf = results["Random Forest"].estimator
        rf = best_rf.named_steps["clf"]
        feat_names = best_rf.named_steps["prep"].get_feature_names_out()
        # strip the "num__"/"cat__" transformer prefixes for readability
        clean_names = [n.split("__", 1)[-1] for n in feat_names]
        importances = pd.Series(rf.feature_importances_, index=clean_names).sort_values()
        importances = importances.tail(12)  # top 12 for a clean chart

        plt.figure(figsize=(8, 6))
        importances.plot(kind="barh", color="#2b8cbe")
        plt.xlabel("Importance (Random Forest)")
        plt.title("Feature Importance — What Drives Churn")
        plt.tight_layout()
        plt.savefig(self.cfg.fi_png, dpi=150)
        plt.close()
        print(f"saved {self.cfg.fi_png}")
        return importances.sort_values(ascending=False)


# ======================================================================
# STEP 5  -  MetricsReporter: dump the raw numbers to JSON
# ======================================================================
class MetricsReporter:
    def __init__(self, config: Config):
        self.cfg = config

    def write(self, results: Dict[str, ModelResult]) -> str:
        summary = {
            name: {**r.metrics, "best_params": r.best_params}
            for name, r in results.items()
        }
        with open(self.cfg.metrics_json, "w") as f:
            json.dump(summary, f, indent=2, default=str)
        print(f"saved {self.cfg.metrics_json}")
        return self.cfg.metrics_json


# ======================================================================
# ChurnPipeline  -  the orchestrator. The STEP ORDER lives here, once.
# ======================================================================
class ChurnPipeline:
    def __init__(self, config: Config = None):
        self.cfg = config or Config()
        os.makedirs(self.cfg.output_dir, exist_ok=True)

        # each collaborator owns exactly one responsibility
        self.dataset_builder = DatasetBuilder(self.cfg)
        self.trainer = ChurnModelTrainer(self.cfg)
        self.evaluator = ModelEvaluator()
        self.figures = FigureBuilder(self.cfg)
        self.reporter = MetricsReporter(self.cfg)

    def run(self):
        print("STEP 1/5  Load + split data")
        data = self.dataset_builder.build()

        print("\nSTEP 2/5  Train + tune models (GridSearchCV)")
        tuned = self.trainer.train(data)

        print("\nSTEP 3/5  Evaluate on held-out test set")
        results = self.evaluator.evaluate(tuned, data)

        print("\nSTEP 4/5  Build figures")
        self.figures.plot_roc(results)
        self.figures.plot_feature_importance(results)

        print("\nSTEP 5/5  Write metrics summary")
        self.reporter.write(results)

        print("\nDone. Figures and metrics are in ./outputs/")
        return results


def main():
    ChurnPipeline().run()


if __name__ == "__main__":
    main()
